quarkus:
  datasource:

    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/tech
    username: user
    password: pass

mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: localhost:9092

    outgoing:
      unsigned-messages:
        connector: smallrye-kafka
        topic: messages.unsigned
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

    incoming:
      signed-messages:
        connector: smallrye-kafka
        topic: messages.signed
        value:
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
        auto:
          offset:
            reset: earliest
        group:
          id: messages

  smallrye-health:
    root-path: /q/health
    ui:
      enabled: true